### PR TITLE
Migrated transforms to robot_state_publisher

### PR DESCRIPTION
**Pull request by amiller27**

### CODE REVIEW

**Comment by asaba96** [comment]
Are you planning on doing the same for the other platforms?

**Comment by amiller27** [comment]
Yeah sure

**Comment by amiller27** [comment]
Done

**Comment by asaba96** [comment]
Have you tested each of them to ensure it works?

**Comment by amiller27** [comment]
Yes

**Review by asaba96 — APPROVED** [review]
Awesome!

**Pull request merged**
